// <auto-generated>
// Generated from libgsa tests/vectors/apple_srp_vector.h by
// tools/gen-srp-vector.py. These are numbers (an SRP golden vector), not
// Apple code; they originate from the MIT `srp` library via libgsa's oracle.
// Do not edit by hand — regenerate from the header instead.
// </auto-generated>

namespace Sideport.GrandSlam.Tests.Vectors;

/// <summary>
/// The Apple GrandSlam SRP-6a golden vector (fixed private exponent), used to
/// pin the managed implementation byte-for-byte against libgsa.
/// </summary>
internal static class AppleSrpVector
{
    public const string Username = "test@example.com";
    public const string Password = "correct horse battery staple";
    public const int Iterations = 1000;

    public static byte[] Salt => Convert.FromHexString("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20");
    public static byte[] FixedA => Convert.FromHexString("800102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff");
    public static byte[] FixedB => Convert.FromHexString("c30b121920272e353c434a51585f666d747b828990979ea5acb3bac1c8cfd6dde4ebf2f900070e151c232a31383f464d545b626970777e858c939aa1a8afb6bdc4cbd2d9e0e7eef5fc030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8bfc6cdd4dbe2e9f0f7fe050c131a21282f363d444b525960676e757c838a91989fa6adb4bbc2c9d0d7dee5ecf3fa01080f161d242b323940474e555c636a71787f868d949ba2a9b0b7bec5ccd3dae1e8eff6fd");
    public static byte[] PasswordKey => Convert.FromHexString("374df2ff47e109b7e525235c43c91266ca9590b2f27ae6d175250fd89389f8d5");
    public static byte[] PublicA => Convert.FromHexString("4846927a9c7fdea6d9d3ce72ac9fbbe02c97b36bb686e7a2ae2b80593786a8af40066cdf87a398f608c608d135462b8a7f66c5e1f76f1f55458424cee6b49a21d333c39aba1956b9fc79ab5574c46668796935da544b2ac6b7de5f29bd07751d0ca2894eb17a4e3760ed8f9dcd460facee4b3ac27829f322c936116051cd1978ecdd1c0e07787f0fa8c3d8e4b068abd94b57e2406863e9e0c7771da47ba45255839b8b7a07db53cc89b3c7410d548caa5f1fe125b93f7f3c23a1e9ba1b1749fdda337cc523bbfd06549e9a8ad6a1c22f2990ab6a69549a17ffb484f1012c92b2865474de14fff29a319a2d46504aa3cbcbeb8a047d52a784e57ad6760b4f0a1c");
    public static byte[] M1 => Convert.FromHexString("9e79217d21ffa09f6e6d87fd8e0070be78b40ddda5f87c372d109de7c11cca17");
    public static byte[] SessionKey => Convert.FromHexString("cde72a8055f7b5e43b8b66708b1cd40b1bbd9c89ca4314ce98de07db34be5ad8");
    public static byte[] M2 => Convert.FromHexString("ff22f7b71f3b4b574080b0541db1f4583a11ea31e89138e4b09ae055b36df171");
    public static byte[] ExtraDataKey => Convert.FromHexString("a3132bc628141210234bbec567feb20eded0f4d02ac10b46f0b7ab14cef690d1");
    public static byte[] ExtraDataIv => Convert.FromHexString("c63bcd9524dd7b7864953cec2b71e5be");
    public static byte[] HmacKey => Convert.FromHexString("d689b5ee1bc87eae8fbd0244aab6d1ac1c7f1c083e377fb296201eb8622e8575");
}
