#!/usr/bin/env python3
"""Generate the C# golden-vector fixture from libgsa's apple_srp_vector.h.

One-shot dev tool: parses the committed C header (numbers only, no Apple code)
and emits tests/Sideport.GrandSlam.Tests/Vectors/AppleSrpVector.cs so the 256-
byte arrays are transcribed mechanically, not by hand.
"""
import re
import sys

HEADER = "/Users/dragoshont/Repo/libgsa/tests/vectors/apple_srp_vector.h"
OUT = "/Users/dragoshont/Repo/sideport/tests/Sideport.GrandSlam.Tests/Vectors/AppleSrpVector.cs"

src = open(HEADER).read()

arrays = {}
for m in re.finditer(r"static const uint8_t (\w+)\[\d+\]\s*=\s*\{([^}]*)\};", src):
    name = m.group(1)
    bytes_ = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", m.group(2))]
    arrays[name] = bytes(bytes_)

username = re.search(r'GSA_VEC_USERNAME\[\]\s*=\s*"([^"]*)"', src).group(1)
password = re.search(r'GSA_VEC_PASSWORD\[\]\s*=\s*"([^"]*)"', src).group(1)
iterations = int(re.search(r"GSA_VEC_ITERATIONS\s*=\s*(\d+)", src).group(1))

# Map C names -> C# property names.
names = {
    "GSA_VEC_SALT": "Salt",
    "GSA_VEC_FIXED_A": "FixedA",
    "GSA_VEC_FIXED_B": "FixedB",
    "GSA_VEC_PWKEY": "PasswordKey",
    "GSA_VEC_A": "PublicA",
    "GSA_VEC_M1": "M1",
    "GSA_VEC_K": "SessionKey",
    "GSA_VEC_M2": "M2",
    "GSA_VEC_EDK": "ExtraDataKey",
    "GSA_VEC_EDIV": "ExtraDataIv",
    "GSA_VEC_HMK": "HmacKey",
}

lines = []
lines.append("// <auto-generated>")
lines.append("// Generated from libgsa tests/vectors/apple_srp_vector.h by")
lines.append("// tools/gen-srp-vector.py. These are numbers (an SRP golden vector), not")
lines.append("// Apple code; they originate from the MIT `srp` library via libgsa's oracle.")
lines.append("// Do not edit by hand — regenerate from the header instead.")
lines.append("// </auto-generated>")
lines.append("")
lines.append("namespace Sideport.GrandSlam.Tests.Vectors;")
lines.append("")
lines.append("/// <summary>")
lines.append("/// The Apple GrandSlam SRP-6a golden vector (fixed private exponent), used to")
lines.append("/// pin the managed implementation byte-for-byte against libgsa.")
lines.append("/// </summary>")
lines.append("internal static class AppleSrpVector")
lines.append("{")
lines.append(f'    public const string Username = "{username}";')
lines.append(f'    public const string Password = "{password}";')
lines.append(f"    public const int Iterations = {iterations};")
lines.append("")
for cname, csname in names.items():
    hexstr = arrays[cname].hex()
    lines.append(f'    public static byte[] {csname} => Convert.FromHexString("{hexstr}");')
lines.append("}")
lines.append("")

open(OUT, "w").write("\n".join(lines))
print(f"wrote {OUT}")
print(f"arrays: {', '.join(arrays.keys())}")
for cname, csname in names.items():
    print(f"  {csname:14} {len(arrays[cname]):3d} bytes")
